name: pythonanywhere-extend

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 1 * *'

jobs:
  netease:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
    - name: 'Extend'
      env:
        SCKEY: ${{ secrets.SCKEY }}
      run: python main.py